articles/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse

app_name = 'articles'
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('<str:article_title>/', views.detail, name='detail'),
    path('<str:article_title>/deal_comment/', views.deal_comment, name='deal_comment')
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls', namespace='articles')),
    #path('accounts/', include('django.contrib.auth.urls')),

]

articles/models.py
from django.db import models

# Create your models here.


class Tag(models.Model):
    content = models.CharField(max_length=100)

    def __str__(self):
        return self.content


class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField(null=True, blank=True)
    pub_date = models.DateTimeField('date published')
    author = models.CharField(max_length=100, default='Liu')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-pub_date']


class Comment(models.Model):
    author = models.CharField(max_length=100)
    context = models.TextField(max_length=1000)
    pub_time = models.DateTimeField('pub time', auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

    def __str__(self):
        return self.context[:20]


class RelationOfArticleAndTag(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

articles/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, _get_queryset
from django.http import HttpResponse, HttpResponseRedirect
from .models import Article, Comment, Tag
from .models import RelationOfArticleAndTag as RAT
from markdown import markdown
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views import generic
# Create your views here.


def index(request):
    return HttpResponse("这是首页")


def detail(request, article_title):
    article = get_object_or_404(Article, title=article_title)
    RAT_list = RAT.objects.filter(article__title=article_title)
    article_tag_list = [obj.tag for obj in RAT_list]
    comment_list = Comment.objects.filter(article__title=article_title)

    content_render_by_markdown = markdown(article.content, extensions=[
                                     'markdown.extensions.extra',
                                     'markdown.extensions.codehilite',
                                     'markdown.extensions.toc',
                                  ])

    context = {'article': article, 'content': content_render_by_markdown, 'comment_list': comment_list,
               'tag_list': tag_list(), 'article_tag_list': article_tag_list}
    return render(request, 'articles/blog_main.html', context)


def home(request):
    article_list = _get_queryset(Article)
    content = {'article_list': article_list, 'tag_list': tag_list()}
    return render(request, 'articles/blog_home.html', content)


@login_required
def deal_comment(request, article_title):
    article = get_object_or_404(Article, title=article_title)
    comment_context = request.POST['comment']
    comment = Comment.objects.create(article=article, context=comment_context, author=request.user.username)
    comment.save()
    return HttpResponseRedirect(reverse('articles:detail', args=(article_title,)))


def tag_list():
    tag_list = Tag.objects.all()
    return tag_list

templates/articles/blog_base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "articles/blog.css" %}" rel="stylesheet">
    <link href="{% static "articles/github.css" %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="{% url 'articles:home' %}">首页</a>
          <!--<a class="blog-nav-item" href="#">New features</a>
          <a class="blog-nav-item" href="#">Press</a>
          <a class="blog-nav-item" href="#">New hires</a>
          <a class="blog-nav-item" href="#">About</a> -->
            {%  if request.user.is_authenticated %}
                <a class="blog-nav-item pull-right" href="{% url 'articles:logout' %}">注销</a>
                <a class="blog-nav-item pull-right" href="#">{{ request.user }}</a>
            {% else %}
            <a class="blog-nav-item pull-right" href="{% url 'articles:login' %}">登录</a>
            {% endif %}
        </nav>
      </div>
    </div>
    <div class="container">
        <div class="row">
            {% include 'articles/blog_header.html' %}
            {% block content%}
            {% endblock %}
            {% include 'articles/sidebar.html' %}
        {% if article_list %}
            {% include 'articles/nav_of_page.html' %}
        {% endif %}
      </div><!-- /.row -->
    </div><!-- /.container -->
    {% include 'articles/blog_footer.html' %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>

templates/articles/blog_comment.html
<form action="{% url 'articles:deal_comment' title %}" method="post">
    {% csrf_token %}
    <label for="comment">您的评论</label>
    <input type="text" name="comment" id="comment">
    <input type="submit">
</form>

templates/articles/blog_comment_input.html
<div class="comment_input">
<form action="{% url 'articles:deal_comment' article.title %}" method="post">
    {% csrf_token %}
    <label for="comment" class="label-control">您的评论</label>
    <textarea class="form-control" rows="3" name="comment" id="comment">您的感想</textarea>
    <br/>
    <button type="submit" class="btn btn-default">发布</button>
</form>
</div>

templates/articles/blog_comment_show.html
<div class="container comment_show_area ">
    {% for comment in comment_list %}
        <div class="row">
        <div class="col-sm-12">
            <p>{{ comment.context }}</p>
            <div class="comment_info">
                <div class="col-sm-6">
                    <small class="comment_time">作者：{{ comment.author }}</small>
                </div>
                <div class="col-sm-6">
                    <small class="comment_time">时间：{{ comment.pub_time }}</small>
                </div>
            </div>
        </div>
        </div>
        <hr/>
    {% endfor %}
</div>

templates/articles/blog_footer.html
 <footer class="blog-footer">
      <p>开发中 <a href="#">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">开发中</a>
      </p>
    </footer>

templates/articles/blog_header.html
 <div class="blog-header">
        <h1 class="blog-title">刘濡轩的博客</h1>
        <p class="lead blog-description">一个基于bootstrap和django的简易博客</p>
      </div>

templates/articles/blog_home.html
{% extends "articles/blog_base.html"%}

{% block title %}
    刘濡轩的博客
{% endblock %}

{% block content %}
    <div class="col-sm-8 blog-main">
    {% for article in article_list %}
        <div class="blog-post">
            <a href={% url "articles:detail" article.title %}>
                <h2 class="blog-post-title">{{ article.title }}</h2>
            </a>
                <p class="blog-post-meta"> by <a href="#">{{ article.author }}</a></p>
                {% if article.content|length > 40 %}
                    {{ article.content|slice:':40' }}......
                    <a href={% url "articles:detail" article.title %}>
                    read more
                    </a>
                {% else %}
                    {{ article.content }}
              {% endif %}
          </div>
          <!-- /.blog-post -->
     {% endfor %}
    </div><!-- bloglist -->
{% endblock %}

templates/articles/blog_main.html
{% extends 'articles/blog_base.html' %}
{% block title %}
    {{ article.title }}
{% endblock %}

{% block content %}
 <div class="col-sm-8 blog-main">

          <div class="blog-post">
            <h2 class="blog-post-title">{{ article.title }}</h2>
            <p class="blog-post-meta">{{ article.pub_date }} <a href="#">{{ article.author }}</a></p>
              <p>{% for tag in article_tag_list %}
                  <a href="#" class="article_tag"> {{ tag }}</a>
                  &nbsp;&nbsp;
              {% endfor %}</p>
          <hr/>

              {{ content|safe }}
          </div><!-- /.blog-post -->
     {% include 'articles/blog_comment_input.html' %}
     <br/>
     {% include 'articles/blog_comment_show.html' %}
        </div><!-- /.blog-main -->
{% endblock %}

templates/articles/nav_of_page.html
<div class="row">
    <div class="col-sm-8">
<nav>
            <ul class="pager">
              <li><a href="#">Previous</a></li>
              <li><a href="#">Next</a></li>
            </ul>
          </nav>
    </div>
</div>

templates/articles/sidebar.html
<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>关于</h4>
            <p>blank</p>
          </div>
          <div class="sidebar-module">
            <h4>标签</h4>
            <ol class="list-unstyled tag_list">
                {% for tag in tag_list %}
              <li><a href="#">{{ tag }}</a></li>
                {% endfor %}
            </ol>
          </div>
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
              <ol class="list-unstyled">
              <li><a href="#">空缺</a></li>
              <li><a href="#">空缺</a></li>
              <li><a href="#">空缺</a></li>
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->